name: React CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: setup node 
        uses: actions/setup-node@v4
        with:
          node-version: 18
        
      - name: Install dependencies
        run: |
          pwd
          npm install
          npm ci
        shell: bash
        
      - name: Build app
        run: npm run build
        shell: bash
      
  s3_sync_job_reusable_workflow:
    uses: shaswattejankar/reusable-workflow-test/.github/workflows/build.yml@main
    secrets:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      
