name: React CI/CD

on:
  push:
    branches:
      - main

jobs:    
  build_and_s3_sync_job_reusable_workflow:
    uses: shaswattejankar/reusable-workflow-test/.github/workflows/build.yml@main
    secrets:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      
