name: React CI/CD

on:
  push:
    branches:
      - main

jobs:
  node_run_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
            node-version: 18
      - name: npm commands
        run: |
          echo "running npm commands now..."
          npm install
          npm ci
          npm run build
          echo "...done!"
        shell: bash
    
  s3_sync_job_reusable_workflow:
    uses: shaswattejankar/reusable-workflow-test/.github/workflows/build.yml@main
    secrets:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      
