name: React CI/CD

on:
  push:
    branches:
      - main

jobs:
  node_run:
    uses: shaswattejankar/reusable-workflow-test/.github/workflows/build.yml@main
    
  s3_sync:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v4
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
          SOURCE_DIR: 'build'      # optional: defaults to entire repository

      
